### ISSUE TITLE
Includes with angled brackets are not being trialed for removal

### ISSUE THREAD

**Issue by kreuzerkrieg** [Wumpf/IncludeToolbox#52]
Looks like you are not even trying to remove it. the <windows.h> has been included (and not needed) however according to the tool it is not on the trial list

> Could not remove #include: 'tinyxml2.h'
> Could not remove #include: 'P...r.h'
> Removed 0 #include directives from 'E...r.cpp'

**Comment by Wumpf** [comment]
I think this worked fine for me. However, by default the first include is not checked for removal since it is expected to be the corresponding header. You can change this setting in: settings > Include Toolbox > Trial and Error Include Removal > Ignore First Include

Can you confirm that that was the issue?

**Comment by kreuzerkrieg** [comment]
correct, this is the issue. so, there is no issue :) except when the first include is a precompiled header and the second one is the corresponding one

**Comment by Wumpf** [comment]
For that there is `(\/|\\|^)$(currentFilename)\.(h|hpp|hxx|inl|c|cpp|cxx)$` in the ignore list by default :)
