### ISSUE TITLE
Trial & Error Include Removal ignores linker error.

### ISSUE THREAD

**Issue by Donaldpherman** [Wumpf/IncludeToolbox#65]
I have the declaration of a function in the global namespace in a header file "aName".  The file with definition include the #include "aName.h" header and builds.  Another project call the function and builds OK.

```
// aName.h
__declspec(dllexport) func(*void,**void,int,int);
// differentName.cpp
#include "aName.h"
func(*void,**void,int,int){
  //some implementation.
}

//differentProject.cpp
//calling the function func.
func(arg,arg2,arg3,arg4);
```

When I run Trial & Error Include Removal on differentName.cpp it removed the #include "aName.h" and give me the message 
Successfully removed #include: 'aName.h'  
Removed 1 #include directives from 'differentName.cpp'

When I try to build the solution I get a linker error.
error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl func

**Comment by Wumpf** [comment]
This is by design. As the name suggests "Trial & Error Include Removal" only tries removing an include and tries if the file in question still compiles.
Judging from your error, unlike what you describe your header seems to declare the function with `__declspec(dllexport)` whereas your duplicated predeclaration (why?) does not, leading the file to compile fine but no longer exporting the symbol

**Comment by Donaldpherman** [comment]
I upgraded my OP a bit.  I don't have a duplicate declaration.

**Comment by Wumpf** [comment]
In your previous description you had, but the important problem is of course still the same: There is nothing preventing aName.h from being removed but then you loose the dllexport specifier since you didn't repeat that for the function defintion
